export const topEDHRcardnames = [
    'Sol Ring',
    'Command Tower',
    'Arcane Signet',
    'Exotic Orchard',
    'Reliquary Tower',
    'Swords to Plowshares',
    'Swiftfoot Boots',
    'Lightning Greaves',
    'Path of Ancestry',
    'Path to Exile',
    'Evolving Wilds',
    'Counterspell',
    'Fellwar Stone',
    'Rogue\'s Passage',
    'Cultivate',
    'Thought Vessel',
    'Blasphemous Act',
    'Myriad Landscape',
    'Farseek',
    'Beast Within',
    'Rampant Growth',
    'Terramorphic Expanse',
    'Chaos Warp',
    'Mind Stone',
    'Bojuka Bog',
    'Nature\'s Lore',
    'Heroic Intervention',
    'Solemn Simulacrum',
    'Kodama\'s Reach',
    'Birds of Paradise',
    'Commander\'s Sphere',
    'Dark Ritual',
    'Rhystic Study',
    'Polluted Delta',
    'An Offer You Can\'t Refuse',
    'Cyclonic Rift',
    'Misty Rainforest',
    'Flooded Strand',
    'Three Visits',
    'Skullclamp',
    'Bloodstained Mire',
    'Windswept Heath',
    'Verdant Catacombs',
    'Scalding Tarn',
    'Wooded Foothills',
    'Marsh Flats',
    'Generous Gift',
    'Negate',
    'Arid Mesa',
    'Watery Grave',
    'Smothering Tithe',
    'Arcane Denial',
    'Demonic Tutor',
    'Ancient Tomb',
    'Reanimate',
    'Temple of the False God',
    'Llanowar Elves',
    'Fabled Passage',
    'Toxic Deluge',
    'Godless Shrine',
    'Breeding Pool',
    'Brainstorm',
    'Urborg, Tomb of Yawgmoth',
    'Hallowed Fountain',
    'Stomping Ground',
    'Esper Sentinel',
    'Fierce Guardianship',
    'Steam Vents',
    'Yavimaya, Cradle of Growth',
    'Chromatic Lantern',
    'Boseiju, Who Endures',
    'Swan Song',
    'Blood Crypt',
    'The One Ring',
    'Sunken Hollow',
    'Sacred Foundry',
    'Feed the Swarm',
    'Overgrown Tomb',
    'Cinder Glade',
    'Deflecting Swat',
    'Temple Garden',
    'Talisman of Dominance',
    'Otawara, Soaring City',
    'Sulfur Falls',
    'Mystic Remora',
    'Eternal Witness',
    'Faithless Looting',
    'Clifftop Retreat',
    'Wayfarer\'s Bauble',
    'Teferi\'s Protection',
    'Phyrexian Arena',
    'Dragonskull Summit',
    'Vandalblast',
    'Jesk\'s Will',
    'Sakura-Tribe Elder',
    'Garruk\'s Uprising',
    'Vampiric Tutor',
    'Canopy Vista',
    'Smoldering Marsh',
    'Prairie Stream',
    'City of Brass',
    'Isolated Chapel',
    'Elvish Mystic',
    'Glacial Fortress',
    'Hinterland Harbor',
    'Cavern of Souls',
    'Enlightened Tutor',
    'Mana Drain',
    'Drowned Catacomb',
    'Lotus Petal',
    'Frantic Search',
    'Urz\'s Saga',
    'Mana Confluence',
    'Shivan Reef',
    'Deadly Rollick',
    'Propaganda',
    'Roaming Throne',
    'Talisman of Creativity',
    'Caves of Koilos',
    'Battlefield Forge',
    'Ashnod\'s Altar',
    'Woodland Cemetery',
    'Talisman of Indulgence',
    'Dimir Signet',
    'Assassin\'s Trophy',
    'Victimize',
    'Mystical Tutor',
    'Deadly Dispute',
    'Morphic Pool',
    'Yavimaya Coast',
    'Rejuvenating Springs',
    'Black Market Connections',
    'Windfall',
    'Farewell',
    'Rootbound Crag',
    'Chrome Mox',
    'Rakdos Signet',
    'Mana Vault',
    'Heral\'s Horn',
    'Training Center',
    'War Room',
    'Talisman of Hierarchy',
    'Ponder',
    'Blood Artist',
    'Sunpetal Grove',
    'Izzet Signet',
    'Talisman of Progress',
    'Abrade',
    'Luxury Suite',
    'Austere Command',
    'Worldly Tutor',
    'Talisman of Conviction',
    'Sea of Clouds',
    'Pongify',
    'Delighted Halfling',
    'Underground River',
    'Lightning Bolt',
    'Llanowar Wastes',
    'Anguished Unmaking',
    'Vault of Champions',
    'Orzhov Signet',
    'Spectator Seating',
    'Sulfurous Springs',
    'Nykthos, Shrine to Nyx',
    'Mystic Sanctuary',
    'Ghostly Prison',
    'Boros Charm',
    'Return of the Wildspeaker',
    'Adarkar Wastes',
    'Reflecting Pool',
    'Tireless Provisioner',
    'Azorius Signet',
    'Big Score',
    'Gemstone Caverns',
    'Force of Will',
    'Cabal Coffers',
    'Impact Tremors',
    'Undergrowth Stadium',
    'Ash Barrens',
    'Rhythm of the Wild',
    'Stroke of Midnight',
    'Prismatic Vista',
    'Command Beacon',
    'Flawless Maneuver',
    'Spire Garden',
    'Mosswort Bridge',
    'Buried Ruin',
    'Beast Whisperer',
    'Bountiful Promenade',
    'Wild Growth',
    'Dreamroot Cascade',
    'Village Rites',
    'Thrill of Possibility',
    'Fyndhorn Elves',
    'Rockfall Vale',
    'Karn\'s Bastion',
    'Idol of Oblivion',
    'Mirkwood Bats',
    'Thran Dynamo',
    'Boros Signet',
    'Preordain',
    'Sensei\'s Divining Top',
    'Growth Spiral',
    'Hardened Scales',
    'Opt',
    'Akroma\'s Will',
    'Night\'s Whisper',
    'Animate Dead',
    'Scute Swarm',
    'Shipwreck Marsh',
    'Mox Amber',
    'Crop Rotation',
    'Rapid Hybridization',
    'Doubling Season',
    'Sign in Blood',
    'Stormcarved Coast',
    'Takenuma, Abandoned Mire',
    'Phyrexian Tower',
    'Mithril Coat',
    'Gamble',
    'Ornithopter of Paradise',
    'Secluded Courtyard',
    'Explore',
    'Professional Face-Breaker',
    'Rishkar\'s Expertise',
    'Unclaimed Territory',
    'Mox Opal',
    'Terminate',
    'Orcish Bowmasters',
    'Storm-Kiln Artist',
    'Syr Konrad, the Grim',
    'Zulaport Cutthroat',
    'Harrow',
    'Sink into Stupor // Soporific Springs',
    'Sword of the Animist',
    'Gray Merchant of Asphodel',
    'The Great Henge',
    'Mox Diamond',
    'Everflowing Chalice',
    'Sylvan Library',
    'Pitiless Plunderer',
    'Karplusan Forest',
    'Grand Abolisher',
    'Three Tree City',
    'Viscera Seer',
    'Etali, Primal Storm',
    'Foundry Inspector',
    'Dovin\'s Veto',
    'Bolas\'s Citadel',
    'Malakir Rebirth // Malakir Mire',
    'Force of Negation',
    'Temple of Epiphany',
    'Decanter of Endless Water',
    'Brushland',
    'Simic Growth Chamber',
    'Academy Manufactor',
    'Basilisk Collar',
    'Temple of Silence',
    'Reality Shift',
    'Diabolic Intent',
    'Fell the Profane // Fell Mire',
    'Panharmonicon',
    'Avenger of Zendikar',
    'Sun Titan',
    'Ragavan, Nimble Pilferer',
    'Reclamation Sage',
    'Haunted Ridge',
    'Deserted Beach',
    'Hullbreaker Horror',
    'Choked Estuary',
    'Patchwork Banner',
    'Archmage Emeritus',
    'Temple of Triumph',
    'Skyshroud Claim',
    'Inspiring Call',
    'Exploration',
    'Dryad of the Ilysian Grove',
    'Temple of Mystery',
    'Snap',
    'Inventors\' Fair',
    'Darksteel Citadel',
    'Seedborn Muse',
    'Azusa, Lost but Seeking',
    'Guardian Project',
    'Temple of Enlightenment',
    'Jungle Shrine',
    'Temple of Deceit',
    'Braids, Arisen Nightmare',
    'Phyrexian Metamorph',
    'Darkwater Catacombs',
    'Overgrown Farmland',
    'Dimir Aqueduct',
    'Infernal Grasp',
    'Bala Ged Recovery // Bala Ged Sanctuary',
    'Morbid Opportunist',
    'Harmonize',
    'Blackblade Reforged',
    'Whispersilk Cloak',
    'Flusterstorm',
    'Underground Sea',
    'Sundown Pass',
    'Lotus Cobra',
    'Foreboding Ruins',
    'Jet Medallion',
    'Phyrexian Altar',
    'Golgari Rot Farm',
    'Utopia Sprawl',
    'Vanquisher\'s Banner',
    'Entomb',
    'The Ozolith',
    'Scavenger Grounds',
    'Damn',
    'Finale of Devastation',
    'Unexpected Windfall',
    'Bloom Tender',
    'Urza\'s Incubator',
    'Jetmir\'s Garden',
    'Shadowspear',
    'Rakdos Charm',
    'Anointed Procession',
    'Crumbling Necropolis',
    'Fortified Village',
    'Port Town',
    'Kindred Discovery',
    'Arcane Sanctum',
    'Nature\'s Claim',
    'Damnation',
    'Exsanguinate',
    'Pact of Negation',
    'Game Trail',
    'Aetherize',
    'Flooded Grove',
    'Dauthi Voidwalker',
    'Go for the Throat',
    'Orzhov Basilica',
    'Temple of Malady',
    'Sevinne\'s Reclamation',
    'Frostboil Snarl',
    'Shamanic Revelation',
    'Ketria Triome',
    'Eiganjo, Seat of the Empire',
    'Seat of the Synod',
    'Izzet Boilerworks',
    'Shattered Sanctum',
    'Nomad Outpost',
    'Aetherflux Reservoir',
    'Rampaging Baloths',
    'Cascade Bluffs',
    'Mana Geyser',
    'Kessig Wolf Run',
    'Baleful Strix',
    'Putrefy',
    'Bastion of Remembrance',
    'Ruby Medallion',
    'Rugged Prairie',
    'Furycalm Snarl',
    'Skycloud Expanse',
    'Volcanic Island',
    'Toski, Bearer of Secrets',
    'Loran of the Third Path',
    'Thassa\'s Oracle',
    'Spara\'s Headquarters',
    'Burnished Hart',
    'Mystic Monastery',
    'Kutzil, Malamet Exemplar',
    'Tropical Island',
    'Anger',
    'Craterhoof Behemoth',
    'Spark Double',
    'Withering Torment',
    'Faerie Mastermind',
    'Tundra',
    'Mondrak, Glory Dominus',
    'Minas Tirith',
    'Spire of Industry',
    'Temple of Malice',
    'Gruul Turf',
    'Despark',
    'Read the Bones',
    'Opulent Palace',
    'Helm of the Host',
    'Zagoth Triome',
    'Frontier Bivouac',
    'Geier Reach Sanitarium',
    'Seething Song',
    'Consider',
    'Buried Alive',
    'Scrubland',
    'Azorius Chancery',
    'Bident of Thassa',
    'Badlands',
    'Untimely Malfunction',
    'Ramunap Excavator',
    'Entish Restoration',
    'Guttersnipe',
    'Underworld Breach',
    'Gilded Lotus',
    'Demolition Field',
    'Seaside Citadel',
    'Branching Evolution',
    'Parallel Lives',
    'Raffine\'s Tower',
    'Red Elemental Blast',
    'Field of the Dead',
    'Boros Garrison',
    'Lotho, Corrupt Shirriff',
    'Kami of Whispered Hopes',
    'Hall of Heliod\'s Generosity',
    'Goldspan Dragon',
    'Land Tax',
    'Forgotten Ancient',
    'Witch Enchanter // Witch-Blessed Meadow',
    'Tainted Field',
    'Shadowblood Ridge',
    'Mystic Forge',
    'Great Furnace',
    'Fetid Heath',
    'Silence',
    'Pyroblast',
    'Blind Obedience',
    'Tatyova, Benthic Druid',
    'Mental Misstep',
    'Diabolic Tutor',
    'Expedition Map',
    'Temple of Abandon',
    'Talisman of Curiosity',
    'Sapphire Medallion',
    'Rakdos Carnarium',
    'Demand Answers',
    'Sungrass Prairie',
    'Xander\'s Lounge',
    'Felidar Retreat',
    'Bedevil',
    'Etherium Sculptor',
    'Supreme Verdict',
    'Dawn\'s Truce',
    'Shifting Woodland',
    'Shineshadow Snarl',
    'Cursed Mirror',
    'Temple of Plenty',
    'Goblin Bombardment',
    'Welcoming Vampire',
    'Authority of the Consuls',
    'Tainted Wood',
    'Evolution Sage',
    'Psychosis Crawler',
    'Liquimetal Torque',
    'Indatha Triome',
    'Sheoldred, the Apocalypse',
    'Taiga',
    'Unnatural Growth',
    'Simian Spirit Guide',
    'Opposition Agent',
    'Bayou',
    'Ephemerate',
    'Savai Triome',
    'Fabricate',
    'Sram, Senior Edificer',
    'Plateau',
    'Ohran Frostfang',
    'Sanguine Bond',
    'Tainted Isle',
    'Tamiyo\'s Safekeeping',
    'Vault of the Archangel',
    'Undercity Sewers',
    'Deathcap Glade',
    'Gaea\'s Cradle',
    'Imperial Seal',
    'Goblin Anarchomancer',
    'Raugrin Triome',
    'Arena of Glory',
    'Selesnya Sanctuary',
    'Unbreakable Formation',
    'Savannah',
    'Maskwood Nexus',
    'Birgi, God of Storytelling // Harnfel, Horn of Bounty',
    'Vito, Thorn of the Dusk Rose',
    'Oracle of Mul Daya',
    'Champion of Lambholt',
    'Ghalta, Primal Hunger',
    'Avacyn\'s Pilgrim',
    'Maze of Ith',
    'Living Death',
    'Necropotence',
    'Walking Ballista',
    'Twilight Mire',
    'The Meathook Massacre',
    'Wishclaw Talisman',
    'Ziatora\'s Proving Ground',
    'Chandra\'s Ignition',
    'Talisman of Resilience',
    'Treasure Vault',
    'Mother of Runes',
    'Strip Mine',
    'Simic Signet',
    'Dread Return',
    'Exquisite Blood',
    'Conduit of Worlds',
    'Selvala, Heart of the Wilds',
    'Valakut Awakening // Valakut Stoneforge',
    'Tainted Peak',
    'Strionic Resonator',
    'Dispatch',
    'Plaza of Heroes',
    'High Market',
    'Displacer Kitten',
    'Academy Ruins',
    'Hedron Archive',
    'Cabal Ritual',
    'Terror of the Peaks',
    'Sandsteppe Citadel',
    'Massacre Wurm',
    'Mossfire Valley',
    'Tribute to the World Tree',
    'Crypt Ghast',
    'Gitaxian Probe',
    'Underground Mortuary',
    'Urza\'s Cave',
    'Soul Warden',
    'Growing Rites of Itlimoc // Itlimoc, Cradle of the Sun',
    'Krosan Grip',
    'Adeline, Resplendent Cathar',
    'Snakeskin Veil',
    'Unwinding Clock',
    'Fanatic of Rhonas',
    'Thespian\'s Stage',
    'Overwhelming Stampede',
    'Ancient Den',
    'Conjurer\'s Closet',
    'Chord of Calling',
    'Mindbreak Trap',
    'Basalt Monolith',
    'Pearl Medallion',
    'Mortify',
    'Sword of Feast and Famine',
    'Commander\'s Plate',
    'Vineglimmer Snarl',
    'Warren Soultrader',
    'Bonders\' Enclave',
    'Emergence Zone',
    'Darksteel Mutation',
    'Accursed Marauder',
    'Cathars\' Crusade',
    'Crucible of Worlds',
    'Worn Powerstone',
    'Green Sun\'s Zenith',
    'Hedge Maze',
    'Wheel of Fortune',
    'Veil of Summer',
    'Beastmaster Ascension',
    'Necroblossom Snarl',
    'Midnight Clock',
    'Tibalt\'s Trickery',
    'Faeburrow Elder',
    'Grave Pact',
    'Arbor Elf',
    'Sanctum Weaver',
    'Ghostly Flicker',
    'Wrath of God',
    'Imperial Recruiter',
    'Mentor of the Meek',
    'Mayhem Devil',
    'Corrupted Conviction',
    'Elas il-Kor, Sadistic Pilgrim',
    'Teferi\'s Ageless Insight',
    'Access Tunnel',
    'Fact or Fiction',
    'Knight of the White Orchid',
    'Ignoble Hierarch',
    'Deathrite Shaman',
    'Laboratory Maniac',
    'Rise of the Dark Realms',
    'Relic of Legends',
    'Mulldrifter',
    'Raucous Theater',
    'All That Glitters',
    'Talisman of Impulse',
    'Elemental Bond',
    'Mirari\'s Wake',
    'Tireless Tracker',
    'Altar of Dementia',
    'Minamo, School at Water\'s Edge',
    'Kenrith\'s Transformation',
    'Wood Elves',
    'Noxious Revival',
    'Culling Ritual',
    'Shizo, Death\'s Storehouse',
    'Treasure Cruise',
    'Rising of the Day',
    'The Reaver Cleaver',
    'Plaguecrafter',
    'Shadowy Backstreet',
    'Carrion Feeder',
    'Return to Nature',
    'Vault of Whispers',
    'Muddle the Mixture',
    'Disciple of Freyalise // Garden of Freyalise',
    'Second Harvest',
    'Forbidden Orchard',
    'Drannith Magistrate',
    'Charcoal Diamond',
    'Archivist of Oghma',
    'Golgari Signet',
    'Six',
    'Dramatic Reversal',
    'Blasphemous Edict',
    'Fire Diamond',
    'Changeling Outcast',
    'Mortuary Mire',
    'Dualcaster Mage',
    'Intangible Virtue',
    'Dig Through Time',
    'Archdruid\'s Charm',
    'Curiosity',
    'Realmwalker',
    'Consecrated Sphinx',
    'Opal Palace',
    'Mistrise Village',
    'Enduring Vitality',
    'Emry, Lurker of the Loch',
    'Graven Cairns',
    'Marionette Apprentice',
    'Warstorm Surge',
    'Black Market',
    'Purphoros, God of the Forge',
    'Sheoldred, Whispering One',
    'Ruinous Ultimatum',
    'Brotherhood Regalia',
    'Windbrisk Heights',
    'Reflections of Littjara',
    'Distant Melody',
    'Torment of Hailfire',
    'Castle Ardenvale',
    'Trouble in Pairs',
    'Ripples of Undeath',
    'Ozolith, the Shattered Spire',
    'Cankerbloom',
    'Ancient Greenwarden',
    'Incubation Druid',
    'Bolt Bend',
    'Springleaf Drum',
    'Shared Animosity',
    'Gruul Signet',
    'Sculpting Steel',
    'Emerald Medallion',
    'Culling the Weak',
    'Grim Tutor',
    'Goblin Electromancer',
    'Greater Good',
    'Ancient Copper Dragon',
    'Open the Armory',
    'Selfless Spirit',
    'Puresteel Paladin',
    'Sea Gate Restoration // Sea Gate, Reborn',
    'Reckless Fireweaver',
    'Bitterblossom',
    'Wizard Class',
    'Reprieve',
    'Sphere of Safety',
    'Sheltered Thicket',
    'Pinnacle Monk // Mystic Peak',
    'Goreclaw, Terror of Qal Sisma',
    'Saw in Half',
    'Nesting Grounds',
    'Commercial District',
    'Castle Locthwain',
    'Bontu\'s Monument',
    'Thundering Falls',
    'Life from the Loam',
    'Niv-Mizzet, Parun',
    'Talrand, Sky Summoner',
    'Talon Gates of Madara',
    'Isochron Scepter',
    'Castle Garenbrig',
    'Scoured Barrens',
    'Savage Lands',
    'Eldritch Evolution',
    'Spelunking',
    'Grim Monolith',
    'Abrupt Decay',
    'Mangara, the Diplomat',
    'Sky Diamond',
    'Cloud Key',
    'Blazemire Verge',
    'Harmonic Prodigy',
    'Chain Reaction',
    'Clever Concealment',
    'Clearwater Pathway // Murkwater Pathway',
    'Blighted Woodland',
    'Aggravated Assault',
    'Ghost Quarter',
    'Trailblazer\'s Boots',
    'Etali, Primal Conqueror // Etali, Primal Sickness',
    'Krosan Verge',
    'Rancor',
    'Elesh Norn, Grand Cenobite',
    'Flowering of the White Tree',
    'Leyline of Anticipation',
    'Elspeth, Sun\'s Champion',
    'Ojer Taq, Deepest Foundation // Temple of Civilization',
    'Howling Mine',
    'Aqueous Form',
    'Loyal Apprentice',
    'Stitcher\'s Supplier',
    'Eladamri\'s Call',
    'Young Pyromancer',
    'Spinerock Knoll',
    'Brightclimb Pathway // Grimclimb Pathway',
    'Grapeshot',
    'Kindred Dominance',
    'Boromir, Warden of the Tower',
    'Resculpt',
    'Ranger-Captain of Eos',
    'Oran-Rief, the Vastwood',
    'Meteor Golem',
    'Tainted Pact',
    'Mesa Enchantress',
    'Chasm Skulker',
    'Borne Upon a Wind',
    'Idyllic Tutor',
    'Lush Portico',
    'Bloodchief Ascension',
    'Palladium Myr',
    'Liliana, Dreadhorde General',
    'Curse of Opulence',
    'Rishkar, Peema Renegade',
    'Ornithopter',
    'Eidolon of Blossoms',
    'Rite of Flame',
    'Kay\'s Ghostform',
    'Lion\'s Eye Diamond',
    'Blightstep Pathway // Searstep Pathway',
    'Brash Taunter',
    'Meticulous Archive',
    'Forgotten Cave',
    'Dispel',
    'Imp\'s Mischief',
    'Hydroelectric Specimen // Hydroelectric Laboratory',
    'Jaheira, Friend of the Forest',
    'Whip of Erebos',
    'The World Tree',
    'Peregrin Took',
    'Aftermath Analyst',
    'Imprisoned in the Moon',
    'Krenko, Tin Street Kingpin',
    'Field of Ruin',
    'Narset, Parter of Veils',
    'Gravecrawler',
    'Reconnaissance Mission',
    'Murder',
    'Serum Visions',
    'Curse of the Swine',
    'Breach the Multiverse',
    'Tyvar\'s Stand',
    'Fleshbag Marauder',
    'Bear Umbra',
    'Avacyn, Angel of Hope',
    'Springbloom Druid',
    'Jungle Hollow',
    'Irrigated Farmland',
    'Reassembling Skeleton',
    'City on Fire',
    'Urza, Lord High Artificer',
    'Fiery Islet',
    'Elves of Deep Shadow',
    'Dryad Arbor',
    'Kodama of the West Tree',
    'Riveteers Overlook',
    'Hellkite Tyrant',
    'Bloodletter of Aclazotz',
    'Caged Sun',
    'Demonic Consultation',
    'Sword of Hearth and Home',
    'Canyon Slough',
    'Sai, Master Thopterist',
    'Destiny Spinner',
    'Tragic Slip',
    'Ayara, First of Locthwain',
    'Needleverge Pathway // Pillarverge Pathway',
    'Danitha Capashen, Paragon',
    'Springheart Nantuko',
    'Throne of Eldraine',
    'Thought Monitor',
    'Hammer of Nazahn',
    'Grim Hireling',
    'Fiery Emancipation',
    'Noble Hierarch',
    'Tempt with Discovery',
    'Void Rend',
    'Nadier\'s Nightblade',
    'Gilded Goose',
    'Haywire Mite',
    'Urza\'s Tower',
    'Gloomlake Verge',
    'Spirited Companion',
    'Scrap Trawler',
    'Urza\'s Mine',
    'Myr Battlesphere',
    'Urza\'s Power Plant',
    'Riverglide Pathway // Lavaglide Pathway',
    'Elvish Spirit Guide',
    'High Tide',
    'Fog',
    'Enchantress\'s Presence',
    'Caretaker\'s Talent',
    'Solphim, Mayhem Dominus',
    'Old Gnawbone',
    'Myr Retriever',
    'Setessan Champion',
    'Sylvan Safekeeper',
    'Dragon Tempest',
    'Ledger Shredder',
    'Chain of Vapor',
    'Thrummingbird',
    'Aurelia, the Warleader',
    'Ashaya, Soul of the Wild',
    'Fetid Pools',
    'Mirror Entity',
    'Heraldic Banner',
    'Overflowing Basin',
    'Mizzix\'s Mastery',
    'The Mycosynth Gardens',
    'Sokenzan, Crucible of Defiance',
    'Scattered Groves',
    'Yawgmoth, Thran Physician',
    'Brain Freeze',
    'Cruel Celebrant',
    'Gyre Sage',
    'Witch\'s Cottage',
    'Forsaken Monument',
    'Decimate',
    'Wayward Swordtooth',
    'Narset\'s Reversal',
    'Cryptolith Rite',
    'Rivendell',
    'Boggart Trawler // Boggart Bog',
    'Warleader\'s Call',
    'Elegant Parlor',
    'Bridgeworks Battle // Tanglespan Bridgeworks',
    'Aesi, Tyrant of Gyre Strait',
    'Banner of Kinship',
    'Gavony Township',
    'Thopter Spy Network',
    'Steel Overseer',
    'Soul\'s Attendant',
    'Wonder',
    'Innkeeper\'s Talent',
    'Castle Vantress',
    'Splendid Reclamation',
    'Sythis, Harvest\'s Hand',
    'Cephalid Coliseum',
    'Loxodon Warhammer',
    'Descent into Avernus',
    'Sigarda\'s Aid',
    'Solve the Equation',
    'Voice of Victory',
    'Flare of Fortitude',
    'Thousand-Year Elixir',
    'Delney, Streetwise Lookout',
    'Dusk // Dawn',
    'Bloodfell Caves',
    'Return the Favor',
    'Padeem, Consul of Innovation',
    'Inspiring Statuary',
    'Ophiomancer',
    'Peregrine Drake',
    'Eerie Interlude',
    'Managorger Hydra',
    'Karmic Guide',
    'The Reality Chip',
    'Disrupt Decorum',
    'Scrawling Crawler',
    'Wilderness Reclamation',
    'Spellskite',
    'Cloudshift',
    'Priest of Titania',
    'Snuff Out',
    'Temur Ascendancy',
    'Coat of Arms',
    'Floodfarm Verge',
    'Tranquil Thicket',
    'Barren Moor',
    'Elesh Norn, Mother of Machines',
    'Archaeomancer\'s Map',
    'Ravenous Chupacabra',
    'Last March of the Ents',
    'Chimil, the Inner Sun',
    'Viridescent Bog',
    'Champio\'s Helm',
    'Thoughtcast',
    'Tezzeret\'s Gambit',
    'Beseech the Mirror',
    'Nettlecyst',
    'Xorn',
    'Vanquish the Horde',
    'Taurean Mauler',
    'All Is Dust',
    'Necromancy',
    'Burgeoning',
    'Dismal Backwater',
    'Ferrous Lake',
    'Phyrexian Reclamation',
    'Talisman of Unity',
    'Tyrite Sanctum',
    'Archaeomancer',
    'Ugin, the Ineffable',
    'Midnight Reaper',
    'Noxious Gearhulk',
    'Kodama of the East Tree',
    'Wear // Tear',
    'Hour of Reckoning',
    'Ichor Wellspring',
    'Sundering Eruption // Volcanic Fissure',
    'Veyran, Voice of Duality',
    'Mystic Gate',
    'Selesnya Signet',
    'Alhammarret\'s Archive',
    'Mines of Moria',
    'Torbran, Thane of Red Fell',
    'Unearth',
    'Spell Pierce',
    'Blade of Selves',
    'Spellseeker',
    'Oketra\'s Monument',
    'Aura Shards',
    'Hunter\'s Insight',
    'Irenicus\'s Vile Duplication',
    'Bitter Triumph',
    'Defile',
    'Cragcrown Pathway // Timbercrown Pathway',
    'Cabaretti Courtyard',
    'Cabal Stronghold',
    'Serra Ascendant',
    'Mindcrank',
    'Steel Hellkite',
    'Nezahal, Primal Tide',
    'Tocasia\'s Welcome',
    'Dictate of Erebos',
    'Thornwood Falls',
    'Wurmcoil Engine',
    'Vesuva',
    'The Gitrog Monster',
    'Agadeem\'s Awakening // Agadeem, the Undercrypt',
    'Bristly Bill, Spine Sower',
    'Revitalizing Repast // Old-Growth Grove',
    'Mechanized Production',
    'Fertile Ground',
    'Swiftwater Cliffs',
    'Pull from Tomorrow',
    'Windborn Muse',
    'Kardur, Doomscourge',
    'Yahenni, Undying Partisan',
    'Wind-Scarred Crag',
    'Up the Beanstalk',
    'Twilight Prophet',
    'Dismember',
    'Castle Embereth',
    'Charismatic Conqueror',
    'Expressive Iteration',
    'Hushwood Verge',
    'Karlach, Fury of Avernus',
    'Fireshrieker',
    'Jhoira\'s Familiar',
    'Barkchannel Pathway // Tidechannel Pathway',
    'Colossus Hammer',
    'Waterlogged Grove',
    'Fumigate',
    'Nyxbloom Ancient',
    'Mockingbird',
    'Collective Resistance',
    'Marble Diamond',
    'Crashing Drawbridge',
    'Razortide Bridge',
    'Ghalta, Stampede Tyrant',
    'Moldervine Reclamation',
    'Strix Serenade',
    'Rewind',
    'Grim Haruspex',
    'Seize the Spoils',
    'Artisan of Kozilek',
    'Teleportation Circle',
    'Jace, Wielder of Mysteries',
    'Magus of the Wheel',
    'Inkshield',
    'Valley Floodcaller',
    'Heliod, Sun-Crowned',
    'Sejiri Shelter // Sejiri Glacier',
    'Fiery Inscription',
    'Zuran Orb',
    'Disenchant',
    'Bastion Protector',
    'Mask of Memory',
    'Tear Asunder',
    'Combat Celebrant',
    'Coruscation Mage',
    'Anim Pakal, Thousandth Moon',
    'Rite of Replication',
    'Into the Flood Maw',
    'Escape Tunnel',
    'Kozilek, Butcher of Truth',
]