export const wordBlacklist = [
    "tor",
    "tain",
    "res",
    "hin",
    "bor",
    "ens",
    "rit",
    "eld",
    // "",
    // "",
    // "",
]

export const topEDHRcardnames = [
    'Sol Ring',
    'Command Tower',
    'Arcane Signet',
    'Exotic Orchard',
    'Reliquary Tower',
    'Swords to Plowshares',
    'Swiftfoot Boots',
    'Lightning Greaves',
    'Path of Ancestry',
    'Path to Exile',
    'Evolving Wilds',
    'Counterspell',
    'Fellwar Stone',
    'Rogue\'s Passage',
    'Cultivate',
    'Thought Vessel',
    'Blasphemous Act',
    'Myriad Landscape',
    'Farseek',
    'Beast Within',
    'Rampant Growth',
    'Terramorphic Expanse',
    'Chaos Warp',
    'Mind Stone',
    'Bojuka Bog',
    'Nature\'s Lore',
    'Heroic Intervention',
    'Solemn Simulacrum',
    'Kodama\'s Reach',
    'Birds of Paradise',
    'Commander\'s Sphere',
    'Dark Ritual',
    'Rhystic Study',
    'Polluted Delta',
    'An Offer You Can\'t Refuse',
    'Cyclonic Rift',
    'Misty Rainforest',
    'Flooded Strand',
    'Three Visits',
    'Skullclamp',
    'Bloodstained Mire',
    'Windswept Heath',
    'Verdant Catacombs',
    'Scalding Tarn',
    'Wooded Foothills',
    'Marsh Flats',
    'Generous Gift',
    'Negate',
    'Arid Mesa',
    'Watery Grave',
    'Smothering Tithe',
    'Arcane Denial',
    'Demonic Tutor',
    'Ancient Tomb',
    'Reanimate',
    'Temple of the False God',
    'Llanowar Elves',
    'Fabled Passage',
    'Toxic Deluge',
    'Godless Shrine',
    'Breeding Pool',
    'Brainstorm',
    'Urborg, Tomb of Yawgmoth',
    'Hallowed Fountain',
    'Stomping Ground',
    'Esper Sentinel',
    'Fierce Guardianship',
    'Steam Vents',
    'Yavimaya, Cradle of Growth',
    'Chromatic Lantern',
    'Boseiju, Who Endures',
    'Swan Song',
    'Blood Crypt',
    'The One Ring',
    'Sunken Hollow',
    'Sacred Foundry',
    'Feed the Swarm',
    'Overgrown Tomb',
    'Cinder Glade',
    'Deflecting Swat',
    'Temple Garden',
    'Talisman of Dominance',
    'Otawara, Soaring City',
    'Sulfur Falls',
    'Mystic Remora',
    'Eternal Witness',
    'Faithless Looting',
    'Clifftop Retreat',
    'Wayfarer\'s Bauble',
    'Teferi\'s Protection',
    'Phyrexian Arena',
    'Dragonskull Summit',
    'Vandalblast',
    'Jesk\'s Will',
    'Sakura-Tribe Elder',
    'Garruk\'s Uprising',
    'Vampiric Tutor',
    'Canopy Vista',
    'Smoldering Marsh',
    'Prairie Stream',
    'City of Brass',
    'Isolated Chapel',
    'Elvish Mystic',
    'Glacial Fortress',
    'Hinterland Harbor',
    'Cavern of Souls',
    'Enlightened Tutor',
    'Mana Drain',
    'Drowned Catacomb',
    'Lotus Petal',
    'Frantic Search',
    'Urz\'s Saga',
    'Mana Confluence',
    'Shivan Reef',
    'Deadly Rollick',
    'Propaganda',
    'Roaming Throne',
    'Talisman of Creativity',
    'Caves of Koilos',
    'Battlefield Forge',
    'Ashnod\'s Altar',
    'Woodland Cemetery',
    'Talisman of Indulgence',
    'Dimir Signet',
    'Assassin\'s Trophy',
    'Victimize',
    'Mystical Tutor',
    'Deadly Dispute',
    'Morphic Pool',
    'Yavimaya Coast',
    'Rejuvenating Springs',
    'Black Market Connections',
    'Windfall',
    'Farewell',
    'Rootbound Crag',
    'Chrome Mox',
    'Rakdos Signet',
    'Mana Vault',
    'Heral\'s Horn',
    'Training Center',
    'War Room',
    'Talisman of Hierarchy',
    'Ponder',
    'Blood Artist',
    'Sunpetal Grove',
    'Izzet Signet',
    'Talisman of Progress',
    'Abrade',
    'Luxury Suite',
    'Austere Command',
    'Worldly Tutor',
    'Talisman of Conviction',
    'Sea of Clouds',
    'Pongify',
    'Delighted Halfling',
    'Underground River',
    'Lightning Bolt',
    'Llanowar Wastes',
    'Anguished Unmaking',
    'Vault of Champions',
    'Orzhov Signet',
    'Spectator Seating',
    'Sulfurous Springs',
    'Nykthos, Shrine to Nyx',
    'Mystic Sanctuary',
    'Ghostly Prison',
    'Boros Charm',
    'Return of the Wildspeaker',
    'Adarkar Wastes',
    'Reflecting Pool',
    'Tireless Provisioner',
    'Azorius Signet',
    'Big Score',
    'Gemstone Caverns',
    'Force of Will',
    'Cabal Coffers',
    'Impact Tremors',
    'Undergrowth Stadium',
    'Ash Barrens',
    'Rhythm of the Wild',
    'Stroke of Midnight',
    'Prismatic Vista',
    'Command Beacon',
    'Flawless Maneuver',
    'Spire Garden',
    'Mosswort Bridge',
    'Buried Ruin',
    'Beast Whisperer',
    'Bountiful Promenade',
    'Wild Growth',
    'Dreamroot Cascade',
    'Village Rites',
    'Thrill of Possibility',
    'Fyndhorn Elves',
    'Rockfall Vale',
    'Karn\'s Bastion',
    'Idol of Oblivion',
    'Mirkwood Bats',
    'Thran Dynamo',
    'Boros Signet',
    'Preordain',
    'Sensei\'s Divining Top',
    'Growth Spiral',
    'Hardened Scales',
    'Opt',
    'Akroma\'s Will',
    'Night\'s Whisper',
    'Animate Dead',
    'Scute Swarm',
    'Shipwreck Marsh',
    'Mox Amber',
    'Crop Rotation',
    'Rapid Hybridization',
    'Doubling Season',
    'Sign in Blood',
    'Stormcarved Coast',
    'Takenuma, Abandoned Mire',
    'Phyrexian Tower',
    'Mithril Coat',
    'Gamble',
    'Ornithopter of Paradise',
    'Secluded Courtyard',
    'Explore',
    'Professional Face-Breaker',
    'Rishkar\'s Expertise',
    'Unclaimed Territory',
    'Mox Opal',
    'Terminate',
    'Orcish Bowmasters',
    'Storm-Kiln Artist',
    'Syr Konrad, the Grim',
    'Zulaport Cutthroat',
    'Harrow',
    'Sink into Stupor // Soporific Springs',
    'Sword of the Animist',
    'Gray Merchant of Asphodel',
    'The Great Henge',
    'Mox Diamond',
    'Everflowing Chalice',
    'Sylvan Library',
    'Pitiless Plunderer',
    'Karplusan Forest',
    'Grand Abolisher',
    'Three Tree City',
    'Viscera Seer',
    'Etali, Primal Storm',
    'Foundry Inspector',
    'Dovin\'s Veto',
    'Bolas\'s Citadel',
    'Malakir Rebirth // Malakir Mire',
    'Force of Negation',
    'Temple of Epiphany',
    'Decanter of Endless Water',
    'Brushland',
    'Simic Growth Chamber',
    'Academy Manufactor',
    'Basilisk Collar',
    'Temple of Silence',
    'Reality Shift',
    'Diabolic Intent',
    'Fell the Profane // Fell Mire',
    'Panharmonicon',
    'Avenger of Zendikar',
    'Sun Titan',
    'Ragavan, Nimble Pilferer',
    'Reclamation Sage',
    'Haunted Ridge',
    'Deserted Beach',
    'Hullbreaker Horror',
    'Choked Estuary',
    'Patchwork Banner',
    'Archmage Emeritus',
    'Temple of Triumph',
    'Skyshroud Claim',
    'Inspiring Call',
    'Exploration',
    'Dryad of the Ilysian Grove',
    'Temple of Mystery',
    'Snap',
    'Inventors\' Fair',
    'Darksteel Citadel',
    'Seedborn Muse',
    'Azusa, Lost but Seeking',
    'Guardian Project',
    'Temple of Enlightenment',
    'Jungle Shrine',
    'Temple of Deceit',
    'Braids, Arisen Nightmare',
    'Phyrexian Metamorph',
    'Darkwater Catacombs',
    'Overgrown Farmland',
    'Dimir Aqueduct',
    'Infernal Grasp',
    'Bala Ged Recovery // Bala Ged Sanctuary',
    'Morbid Opportunist',
    'Harmonize',
    'Blackblade Reforged',
    'Whispersilk Cloak',
    'Flusterstorm',
    'Underground Sea',
    'Sundown Pass',
    'Lotus Cobra',
    'Foreboding Ruins',
    'Jet Medallion',
    'Phyrexian Altar',
    'Golgari Rot Farm',
    'Utopia Sprawl',
    'Vanquisher\'s Banner',
    'Entomb',
    'The Ozolith',
    'Scavenger Grounds',
    'Damn',
    'Finale of Devastation',
    'Unexpected Windfall',
    'Bloom Tender',
    'Urza\'s Incubator',
    'Jetmir\'s Garden',
    'Shadowspear',
    'Rakdos Charm',
    'Anointed Procession',
    'Crumbling Necropolis',
    'Fortified Village',
    'Port Town',
    'Kindred Discovery',
    'Arcane Sanctum',
    'Nature\'s Claim',
    'Damnation',
    'Exsanguinate',
    'Pact of Negation',
    'Game Trail',
    'Aetherize',
    'Flooded Grove',
    'Dauthi Voidwalker',
    'Go for the Throat',
    'Orzhov Basilica',
    'Temple of Malady',
    'Sevinne\'s Reclamation',
    'Frostboil Snarl',
    'Shamanic Revelation',
    'Ketria Triome',
    'Eiganjo, Seat of the Empire',
    'Seat of the Synod',
    'Izzet Boilerworks',
    'Shattered Sanctum',
    'Nomad Outpost',
    'Aetherflux Reservoir',
    'Rampaging Baloths',
    'Cascade Bluffs',
    'Mana Geyser',
    'Kessig Wolf Run',
    'Baleful Strix',
    'Putrefy',
    'Bastion of Remembrance',
    'Ruby Medallion',
    'Rugged Prairie',
    'Furycalm Snarl',
    'Skycloud Expanse',
    'Volcanic Island',
    'Toski, Bearer of Secrets',
    'Loran of the Third Path',
    'Thassa\'s Oracle',
    'Spara\'s Headquarters',
    'Burnished Hart',
    'Mystic Monastery',
    'Kutzil, Malamet Exemplar',
    'Tropical Island',
    'Anger',
    'Craterhoof Behemoth',
    'Spark Double',
    'Withering Torment',
    'Faerie Mastermind',
    'Tundra',
    'Mondrak, Glory Dominus',
    'Minas Tirith',
    'Spire of Industry',
    'Temple of Malice',
    'Gruul Turf',
    'Despark',
    'Read the Bones',
    'Opulent Palace',
    'Helm of the Host',
    'Zagoth Triome',
    'Frontier Bivouac',
    'Geier Reach Sanitarium',
    'Seething Song',
    'Consider',
    'Buried Alive',
    'Scrubland',
    'Azorius Chancery',
    'Bident of Thassa',
    'Badlands',
    'Untimely Malfunction',
    'Ramunap Excavator',
    'Entish Restoration',
    'Guttersnipe',
    'Underworld Breach',
    'Gilded Lotus',
    'Demolition Field',
    'Seaside Citadel',
    'Branching Evolution',
    'Parallel Lives',
    'Raffine\'s Tower',
    'Red Elemental Blast',
    'Field of the Dead',
    'Boros Garrison',
    'Lotho, Corrupt Shirriff',
    'Kami of Whispered Hopes',
    'Hall of Heliod\'s Generosity',
    'Goldspan Dragon',
    'Land Tax',
    'Forgotten Ancient',
    'Witch Enchanter // Witch-Blessed Meadow',
    'Tainted Field',
    'Shadowblood Ridge',
    'Mystic Forge',
    'Great Furnace',
    'Fetid Heath',
    'Silence',
    'Pyroblast',
    'Blind Obedience',
    'Tatyova, Benthic Druid',
    'Mental Misstep',
    'Diabolic Tutor',
    'Expedition Map',
    'Temple of Abandon',
    'Talisman of Curiosity',
    'Sapphire Medallion',
    'Rakdos Carnarium',
    'Demand Answers',
    'Sungrass Prairie',
    'Xander\'s Lounge',
    'Felidar Retreat',
    'Bedevil',
    'Etherium Sculptor',
    'Supreme Verdict',
    'Dawn\'s Truce',
    'Shifting Woodland',
    'Shineshadow Snarl',
    'Cursed Mirror',
    'Temple of Plenty',
    'Goblin Bombardment',
    'Welcoming Vampire',
    'Authority of the Consuls',
    'Tainted Wood',
    'Evolution Sage',
    'Psychosis Crawler',
    'Liquimetal Torque',
    'Indatha Triome',
    'Sheoldred, the Apocalypse',
    'Taiga',
    'Unnatural Growth',
    'Simian Spirit Guide',
    'Opposition Agent',
    'Bayou',
    'Ephemerate',
    'Savai Triome',
    'Fabricate',
    'Sram, Senior Edificer',
    'Plateau',
    'Ohran Frostfang',
    'Sanguine Bond',
    'Tainted Isle',
    'Tamiyo\'s Safekeeping',
    'Vault of the Archangel',
    'Undercity Sewers',
    'Deathcap Glade',
    'Gaea\'s Cradle',
    'Imperial Seal',
    'Goblin Anarchomancer',
    'Raugrin Triome',
    'Arena of Glory',
    'Selesnya Sanctuary',
    'Unbreakable Formation',
    'Savannah',
    'Maskwood Nexus',
    'Birgi, God of Storytelling // Harnfel, Horn of Bounty',
    'Vito, Thorn of the Dusk Rose',
    'Oracle of Mul Daya',
    'Champion of Lambholt',
    'Ghalta, Primal Hunger',
    'Avacyn\'s Pilgrim',
    'Maze of Ith',
    'Living Death',
    'Necropotence',
    'Walking Ballista',
    'Twilight Mire',
    'The Meathook Massacre',
    'Wishclaw Talisman',
    'Ziatora\'s Proving Ground',
    'Chandra\'s Ignition',
    'Talisman of Resilience',
    'Treasure Vault',
    'Mother of Runes',
    'Strip Mine',
    'Simic Signet',
    'Dread Return',
    'Exquisite Blood',
    'Conduit of Worlds',
    'Selvala, Heart of the Wilds',
    'Valakut Awakening // Valakut Stoneforge',
    'Tainted Peak',
    'Strionic Resonator',
    'Dispatch',
    'Plaza of Heroes',
    'High Market',
    'Displacer Kitten',
    'Academy Ruins',
    'Hedron Archive',
    'Cabal Ritual',
    'Terror of the Peaks',
    'Sandsteppe Citadel',
    'Massacre Wurm',
    'Mossfire Valley',
    'Tribute to the World Tree',
    'Crypt Ghast',
    'Gitaxian Probe',
    'Underground Mortuary',
    'Urza\'s Cave',
    'Soul Warden',
    'Growing Rites of Itlimoc // Itlimoc, Cradle of the Sun',
    'Krosan Grip',
    'Adeline, Resplendent Cathar',
    'Snakeskin Veil',
    'Unwinding Clock',
    'Fanatic of Rhonas',
    'Thespian\'s Stage',
    'Overwhelming Stampede',
    'Ancient Den',
    'Conjurer\'s Closet',
    'Chord of Calling',
    'Mindbreak Trap',
    'Basalt Monolith',
    'Pearl Medallion',
    'Mortify',
    'Sword of Feast and Famine',
    'Commander\'s Plate',
    'Vineglimmer Snarl',
    'Warren Soultrader',
    'Bonders\' Enclave',
    'Emergence Zone',
    'Darksteel Mutation',
    'Accursed Marauder',
    'Cathars\' Crusade',
    'Crucible of Worlds',
    'Worn Powerstone',
    'Green Sun\'s Zenith',
    'Hedge Maze',
    'Wheel of Fortune',
    'Veil of Summer',
    'Beastmaster Ascension',
    'Necroblossom Snarl',
    'Midnight Clock',
    'Tibalt\'s Trickery',
    'Faeburrow Elder',
    'Grave Pact',
    'Arbor Elf',
    'Sanctum Weaver',
    'Ghostly Flicker',
    'Wrath of God',
    'Imperial Recruiter',
    'Mentor of the Meek',
    'Mayhem Devil',
    'Corrupted Conviction',
    'Elas il-Kor, Sadistic Pilgrim',
    'Teferi\'s Ageless Insight',
    'Access Tunnel',
    'Fact or Fiction',
    'Knight of the White Orchid',
    'Ignoble Hierarch',
    'Deathrite Shaman',
    'Laboratory Maniac',
    'Rise of the Dark Realms',
    'Relic of Legends',
    'Mulldrifter',
    'Raucous Theater',
    'All That Glitters',
    'Talisman of Impulse',
    'Elemental Bond',
    'Mirari\'s Wake',
    'Tireless Tracker',
    'Altar of Dementia',
    'Minamo, School at Water\'s Edge',
    'Kenrith\'s Transformation',
    'Wood Elves',
    'Noxious Revival',
    'Culling Ritual',
    'Shizo, Death\'s Storehouse',
    'Treasure Cruise',
    'Rising of the Day',
    'The Reaver Cleaver',
    'Plaguecrafter',
    'Shadowy Backstreet',
    'Carrion Feeder',
    'Return to Nature',
    'Vault of Whispers',
    'Muddle the Mixture',
    'Disciple of Freyalise // Garden of Freyalise',
    'Second Harvest',
    'Forbidden Orchard',
    'Drannith Magistrate',
    'Charcoal Diamond',
    'Archivist of Oghma',
    'Golgari Signet',
    'Six',
    'Dramatic Reversal',
    'Blasphemous Edict',
    'Fire Diamond',
    'Changeling Outcast',
    'Mortuary Mire',
    'Dualcaster Mage',
    'Intangible Virtue',
    'Dig Through Time',
    'Archdruid\'s Charm',
    'Curiosity',
    'Realmwalker',
    'Consecrated Sphinx',
    'Opal Palace',
    'Mistrise Village',
    'Enduring Vitality',
    'Emry, Lurker of the Loch',
    'Graven Cairns',
    'Marionette Apprentice',
    'Warstorm Surge',
    'Black Market',
    'Purphoros, God of the Forge',
    'Sheoldred, Whispering One',
    'Ruinous Ultimatum',
    'Brotherhood Regalia',
    'Windbrisk Heights',
    'Reflections of Littjara',
    'Distant Melody',
    'Torment of Hailfire',
    'Castle Ardenvale',
    'Trouble in Pairs',
    'Ripples of Undeath',
    'Ozolith, the Shattered Spire',
    'Cankerbloom',
    'Ancient Greenwarden',
    'Incubation Druid',
    'Bolt Bend',
    'Springleaf Drum',
    'Shared Animosity',
    'Gruul Signet',
    'Sculpting Steel',
    'Emerald Medallion',
    'Culling the Weak',
    'Grim Tutor',
    'Goblin Electromancer',
    'Greater Good',
    'Ancient Copper Dragon',
    'Open the Armory',
    'Selfless Spirit',
    'Puresteel Paladin',
    'Sea Gate Restoration // Sea Gate, Reborn',
    'Reckless Fireweaver',
    'Bitterblossom',
    'Wizard Class',
    'Reprieve',
    'Sphere of Safety',
    'Sheltered Thicket',
    'Pinnacle Monk // Mystic Peak',
    'Goreclaw, Terror of Qal Sisma',
    'Saw in Half',
    'Nesting Grounds',
    'Commercial District',
    'Castle Locthwain',
    'Bontu\'s Monument',
    'Thundering Falls',
    'Life from the Loam',
    'Niv-Mizzet, Parun',
    'Talrand, Sky Summoner',
    'Talon Gates of Madara',
    'Isochron Scepter',
    'Castle Garenbrig',
    'Scoured Barrens',
    'Savage Lands',
    'Eldritch Evolution',
    'Spelunking',
    'Grim Monolith',
    'Abrupt Decay',
    'Mangara, the Diplomat',
    'Sky Diamond',
    'Cloud Key',
    'Blazemire Verge',
    'Harmonic Prodigy',
    'Chain Reaction',
    'Clever Concealment',
    'Clearwater Pathway // Murkwater Pathway',
    'Blighted Woodland',
    'Aggravated Assault',
    'Ghost Quarter',
    'Trailblazer\'s Boots',
    'Etali, Primal Conqueror // Etali, Primal Sickness',
    'Krosan Verge',
    'Rancor',
    'Elesh Norn, Grand Cenobite',
    'Flowering of the White Tree',
    'Leyline of Anticipation',
    'Elspeth, Sun\'s Champion',
    'Ojer Taq, Deepest Foundation // Temple of Civilization',
    'Howling Mine',
    'Aqueous Form',
    'Loyal Apprentice',
    'Stitcher\'s Supplier',
    'Eladamri\'s Call',
    'Young Pyromancer',
    'Spinerock Knoll',
    'Brightclimb Pathway // Grimclimb Pathway',
    'Grapeshot',
    'Kindred Dominance',
    'Boromir, Warden of the Tower',
    'Resculpt',
    'Ranger-Captain of Eos',
    'Oran-Rief, the Vastwood',
    'Meteor Golem',
    'Tainted Pact',
    'Mesa Enchantress',
    'Chasm Skulker',
    'Borne Upon a Wind',
    'Idyllic Tutor',
    'Lush Portico',
    'Bloodchief Ascension',
    'Palladium Myr',
    'Liliana, Dreadhorde General',
    'Curse of Opulence',
    'Rishkar, Peema Renegade',
    'Ornithopter',
    'Eidolon of Blossoms',
    'Rite of Flame',
    'Kay\'s Ghostform',
    'Lion\'s Eye Diamond',
    'Blightstep Pathway // Searstep Pathway',
    'Brash Taunter',
    'Meticulous Archive',
    'Forgotten Cave',
    'Dispel',
    'Imp\'s Mischief',
    'Hydroelectric Specimen // Hydroelectric Laboratory',
    'Jaheira, Friend of the Forest',
    'Whip of Erebos',
    'The World Tree',
    'Peregrin Took',
    'Aftermath Analyst',
    'Imprisoned in the Moon',
    'Krenko, Tin Street Kingpin',
    'Field of Ruin',
    'Narset, Parter of Veils',
    'Gravecrawler',
    'Reconnaissance Mission',
    'Murder',
    'Serum Visions',
    'Curse of the Swine',
    'Breach the Multiverse',
    'Tyvar\'s Stand',
    'Fleshbag Marauder',
    'Bear Umbra',
    'Avacyn, Angel of Hope',
    'Springbloom Druid',
    'Jungle Hollow',
    'Irrigated Farmland',
    'Reassembling Skeleton',
    'City on Fire',
    'Urza, Lord High Artificer',
    'Fiery Islet',
    'Elves of Deep Shadow',
    'Dryad Arbor',
    'Kodama of the West Tree',
    'Riveteers Overlook',
    'Hellkite Tyrant',
    'Bloodletter of Aclazotz',
    'Caged Sun',
    'Demonic Consultation',
    'Sword of Hearth and Home',
    'Canyon Slough',
    'Sai, Master Thopterist',
    'Destiny Spinner',
    'Tragic Slip',
    'Ayara, First of Locthwain',
    'Needleverge Pathway // Pillarverge Pathway',
    'Danitha Capashen, Paragon',
    'Springheart Nantuko',
    'Throne of Eldraine',
    'Thought Monitor',
    'Hammer of Nazahn',
    'Grim Hireling',
    'Fiery Emancipation',
    'Noble Hierarch',
    'Tempt with Discovery',
    'Void Rend',
    'Nadier\'s Nightblade',
    'Gilded Goose',
    'Haywire Mite',
    'Urza\'s Tower',
    'Gloomlake Verge',
    'Spirited Companion',
    'Scrap Trawler',
    'Urza\'s Mine',
    'Myr Battlesphere',
    'Urza\'s Power Plant',
    'Riverglide Pathway // Lavaglide Pathway',
    'Elvish Spirit Guide',
    'High Tide',
    'Fog',
    'Enchantress\'s Presence',
    'Caretaker\'s Talent',
    'Solphim, Mayhem Dominus',
    'Old Gnawbone',
    'Myr Retriever',
    'Setessan Champion',
    'Sylvan Safekeeper',
    'Dragon Tempest',
    'Ledger Shredder',
    'Chain of Vapor',
    'Thrummingbird',
    'Aurelia, the Warleader',
    'Ashaya, Soul of the Wild',
    'Fetid Pools',
    'Mirror Entity',
    'Heraldic Banner',
    'Overflowing Basin',
    'Mizzix\'s Mastery',
    'The Mycosynth Gardens',
    'Sokenzan, Crucible of Defiance',
    'Scattered Groves',
    'Yawgmoth, Thran Physician',
    'Brain Freeze',
    'Cruel Celebrant',
    'Gyre Sage',
    'Witch\'s Cottage',
    'Forsaken Monument',
    'Decimate',
    'Wayward Swordtooth',
    'Narset\'s Reversal',
    'Cryptolith Rite',
    'Rivendell',
    'Boggart Trawler // Boggart Bog',
    'Warleader\'s Call',
    'Elegant Parlor',
    'Bridgeworks Battle // Tanglespan Bridgeworks',
    'Aesi, Tyrant of Gyre Strait',
    'Banner of Kinship',
    'Gavony Township',
    'Thopter Spy Network',
    'Steel Overseer',
    'Soul\'s Attendant',
    'Wonder',
    'Innkeeper\'s Talent',
    'Castle Vantress',
    'Splendid Reclamation',
    'Sythis, Harvest\'s Hand',
    'Cephalid Coliseum',
    'Loxodon Warhammer',
    'Descent into Avernus',
    'Sigarda\'s Aid',
    'Solve the Equation',
    'Voice of Victory',
    'Flare of Fortitude',
    'Thousand-Year Elixir',
    'Delney, Streetwise Lookout',
    'Dusk // Dawn',
    'Bloodfell Caves',
    'Return the Favor',
    'Padeem, Consul of Innovation',
    'Inspiring Statuary',
    'Ophiomancer',
    'Peregrine Drake',
    'Eerie Interlude',
    'Managorger Hydra',
    'Karmic Guide',
    'The Reality Chip',
    'Disrupt Decorum',
    'Scrawling Crawler',
    'Wilderness Reclamation',
    'Spellskite',
    'Cloudshift',
    'Priest of Titania',
    'Snuff Out',
    'Temur Ascendancy',
    'Coat of Arms',
    'Floodfarm Verge',
    'Tranquil Thicket',
    'Barren Moor',
    'Elesh Norn, Mother of Machines',
    'Archaeomancer\'s Map',
    'Ravenous Chupacabra',
    'Last March of the Ents',
    'Chimil, the Inner Sun',
    'Viridescent Bog',
    'Champio\'s Helm',
    'Thoughtcast',
    'Tezzeret\'s Gambit',
    'Beseech the Mirror',
    'Nettlecyst',
    'Xorn',
    'Vanquish the Horde',
    'Taurean Mauler',
    'All Is Dust',
    'Necromancy',
    'Burgeoning',
    'Dismal Backwater',
    'Ferrous Lake',
    'Phyrexian Reclamation',
    'Talisman of Unity',
    'Tyrite Sanctum',
    'Archaeomancer',
    'Ugin, the Ineffable',
    'Midnight Reaper',
    'Noxious Gearhulk',
    'Kodama of the East Tree',
    'Wear // Tear',
    'Hour of Reckoning',
    'Ichor Wellspring',
    'Sundering Eruption // Volcanic Fissure',
    'Veyran, Voice of Duality',
    'Mystic Gate',
    'Selesnya Signet',
    'Alhammarret\'s Archive',
    'Mines of Moria',
    'Torbran, Thane of Red Fell',
    'Unearth',
    'Spell Pierce',
    'Blade of Selves',
    'Spellseeker',
    'Oketra\'s Monument',
    'Aura Shards',
    'Hunter\'s Insight',
    'Irenicus\'s Vile Duplication',
    'Bitter Triumph',
    'Defile',
    'Cragcrown Pathway // Timbercrown Pathway',
    'Cabaretti Courtyard',
    'Cabal Stronghold',
    'Serra Ascendant',
    'Mindcrank',
    'Steel Hellkite',
    'Nezahal, Primal Tide',
    'Tocasia\'s Welcome',
    'Dictate of Erebos',
    'Thornwood Falls',
    'Wurmcoil Engine',
    'Vesuva',
    'The Gitrog Monster',
    'Agadeem\'s Awakening // Agadeem, the Undercrypt',
    'Bristly Bill, Spine Sower',
    'Revitalizing Repast // Old-Growth Grove',
    'Mechanized Production',
    'Fertile Ground',
    'Swiftwater Cliffs',
    'Pull from Tomorrow',
    'Windborn Muse',
    'Kardur, Doomscourge',
    'Yahenni, Undying Partisan',
    'Wind-Scarred Crag',
    'Up the Beanstalk',
    'Twilight Prophet',
    'Dismember',
    'Castle Embereth',
    'Charismatic Conqueror',
    'Expressive Iteration',
    'Hushwood Verge',
    'Karlach, Fury of Avernus',
    'Fireshrieker',
    'Jhoira\'s Familiar',
    'Barkchannel Pathway // Tidechannel Pathway',
    'Colossus Hammer',
    'Waterlogged Grove',
    'Fumigate',
    'Nyxbloom Ancient',
    'Mockingbird',
    'Collective Resistance',
    'Marble Diamond',
    'Crashing Drawbridge',
    'Razortide Bridge',
    'Ghalta, Stampede Tyrant',
    'Moldervine Reclamation',
    'Strix Serenade',
    'Rewind',
    'Grim Haruspex',
    'Seize the Spoils',
    'Artisan of Kozilek',
    'Teleportation Circle',
    'Jace, Wielder of Mysteries',
    'Magus of the Wheel',
    'Inkshield',
    'Valley Floodcaller',
    'Heliod, Sun-Crowned',
    'Sejiri Shelter // Sejiri Glacier',
    'Fiery Inscription',
    'Zuran Orb',
    'Disenchant',
    'Bastion Protector',
    'Mask of Memory',
    'Tear Asunder',
    'Combat Celebrant',
    'Coruscation Mage',
    'Anim Pakal, Thousandth Moon',
    'Rite of Replication',
    'Into the Flood Maw',
    'Escape Tunnel',
    'Kozilek, Butcher of Truth',
    'Vision Skeins',
    'Artful Dodge',
    'Dark Petition',
    'Hinterland Sanctifier',
    'Blazing Crescendo',
    'Bayek of Siwa',
    'Mechtitan Core',
    'Théoden, King of Rohan',
    'Chittering Dispatcher',
    'Mox Tantalite',
    'Lumbering Falls',
    'Zack Fair',
    'Defiler of Instinct',
    'Fist of Suns',
    'Merfolk Sovereign',
    'Selective Obliteration',
    'Assault Suit',
    'Serum Snare',
    'Shield of the Oversoul',
    'Verity Circle',
    'Ao, the Dawn Sky',
    'Bag of Holding',
    'Primordial Sage',
    'Mirelurk Queen',
    'Mandate of Abaddon',
    'Éowyn, Shieldmaiden',
    'Shadowgrange Archfiend',
    'Hidden Cataract',
    'Doomskar',
    'Tivit, Seller of Secrets',
    'Dark Prophecy',
    'Danitha, Benalia\'s Hope',
    'Squirming Emergence',
    'Transpose',
    'Indomitable Might',
    'Wojek Investigator',
    'Labyrinth of Skophos',
    'Leap',
    'Folk Hero',
    'Kalain, Reclusive Painter',
    'The Golden Throne',
    'Dissipation Field',
    'Traxos, Scourge of Kroog',
    'Nemata, Primeval Warden',
    'Sandstone Oracle',
    'Sword of Once and Future',
    'Emperor Mihail II',
    'Overcharged Amalgam',
    'Two-Headed Hellkite',
    'Unstable Obelisk',
    'Healer\'s Hawk',
    'Noxious Ghoul',
    'Grasslands',
    'Drogskol Reaver',
    'Curate',
    'Zara, Renegade Recruiter',
    'On the Trail',
    'Peacewalker Colossus',
    'Killian, Ink Duelist',
    'Come Back Wrong',
    'Rally the Ranks',
    'Defiler of Faith',
    'Vicious Rumors',
    'Back in Town',
    'Primal Might',
    'Shadow of the Second Sun',
    'Altar\'s Reap',
    'Heronblade Elite',
    'Nemesis of Reason',
    'Alrund\'s Epiphany',
    'Minn, Wily Illusionist',
    'Zo-Zu the Punisher',
    'Desert',
    'Frogify',
    'Swashbuckler Extraordinaire',
    'The Regalia',
    'Voidslime',
    'Mind Flayer',
    'Theater of Horrors',
    'Blacksmith\'s Talent',
    'Xenagos, the Reveler',
    'Unfinished Business',
    'Baron Bertram Graywater',
    'Captain N\'ghathrod',
    'Restless Vents',
    'Akroma, Angel of Wrath',
    'Cut Down',
    'Atla Palani, Nest Tender',
    'Revitalize',
    'Death Kiss',
    'Angel of Finality',
    'Tinybones Joins Up',
    'Bloodbraid Elf',
    'Goblin Rabblemaster',
    'Keep Watch',
    'Strixhaven Stadium',
    'Death\'s Presence',
    'Thalia\'s Lieutenant',
    'Determined Iteration',
    'Teferi, Hero of Dominaria',
    'Innocent Blood',
    'Research Thief',
    'Turnabout',
    'Shadow of Mortality',
    'Helm of the Gods',
    'Idyllic Grange',
    'Fevered Visions',
    'Yoshimaru, Ever Faithful',
    'Joraga Warcaller',
    'Kruphix, God of Horizons',
    'Dionus, Elvish Archdruid',
    'Sea-Dasher Octopus',
    'Vizier of Many Faces',
    'Desert of the Glorified',
    'Impervious Greatwurm',
    'Aminatou, the Fateshifter',
    'Displaced Dinosaurs',
    'Heartbeat of Spring',
    'Lifecreed Duo',
    'Kiora Bests the Sea God',
    'Adriana, Captain of the Guard',
    'Securitron Squadron',
    'Grave Betrayal',
    'Polymorphist\'s Jest',
    'Component Pouch',
    'Nahiri\'s Lithoforming',
    'Knollspine Dragon',
    'Cyber Conversion',
    'Nested Shambler',
    'Mendicant Core, Guidelight',
    'Stormsplitter',
    'Eagle Vision',
    'Digsite Engineer',
    'Open the Gates',
    'Flamerush Rider',
    'Kamahl, Heart of Krosa',
    'Everything Comes to Dust',
    'Wand of Orcus',
    'Bloodroot Apothecary',
    'Thraben Charm',
    'Blade Splicer',
    'Volatile Fjord',
    'Keiga, the Tide Star',
    'Tegwyll, Duke of Splendor',
    'Tavern Scoundrel',
    'Titania, Voice of Gaea',
    'Sage of the Beyond',
    'Unsettled Mariner',
    'Dragonstorm Globe',
    'From Beyond',
    'Teferi, Who Slows the Sunset',
    'Foil',
    'Compulsive Research',
    'Tidal Barracuda',
    'Fireball',
    'Notorious Throng',
    'Bottle-Cap Blast',
    'Marisi, Breaker of the Coil',
    'Tyrant\'s Familiar',
    'Slash the Ranks',
    'Urza, Chief Artificer',
    'Gothmog, Morgul Lieutenant',
    'Nanogene Conversion',
    'Spawning Pit',
    'Archetype of Courage',
    'Light of Promise',
    'Breaker of Creation',
    'Cryptic Caves',
    'Atzocan Seer',
    'Defiler of Dreams',
    'Vexing Shusher',
    'Wild Wasteland',
    'Pilgrim\'s Eye',
    'Scavenger\'s Talent',
    'Ulalek, Fused Atrocity',
    'Monstrous Rage',
    'Cerulean Wisps',
    'Purphoros, Bronze-Blooded',
    'Liliana\'s Triumph',
    'Nezumi Informant',
    'Deeproot Waters',
    'Tomb Fortress',
    'Syphon Sliver',
    'Azusa\'s Many Journeys // Likeness of the Seeker',
    'Glowing One',
    'Astor, Bearer of Blades',
    'Angelic Field Marshal',
    'Darien, King of Kjeldor',
    'Star Compass',
    'Slinn Voda, the Rising Deep',
    'Underworld Connections',
    'Drannith Ruins',
    'Necron Deathmark',
    'Judith, Carnage Connoisseur',
    'Preacher of the Schism',
    'Muxus, Goblin Grandee',
    'Wall of Frost',
    'Eternal Skylord',
    'Snapping Voidcraw',
    'Cruel Somnophage // Can\'t Wake Up',
    'Atalan Jackal',
    'Manakin',
    'Liliana\'s Mastery',
    'Crypt Incursion',
    'Sultai Charm',
    'Mission Briefing',
    'Calix, Destiny\'s Hand',
    'Titan of Industry',
    'Wulfgar of Icewind Dale',
    'Azure Beastbinder',
    'Merfolk Looter',
    'Cathartic Pyre',
    'Vizier of the Menagerie',
    'Victory Chimes',
    'Sazh\'s Chocobo',
    'Surgehacker Mech',
    'Planar Bridge',
    'Rammas Echor, Ancient Shield',
    'March of the Canonized',
    'Bringer of the Last Gift',
    'Throne of the High City',
    'Reject Imperfection',
    'Spellstutter Sprite',
    'Thran Portal',
    'Ultimate Magic: Holy',
    'Peek',
    'Lonis, Cryptozoologist',
    'Yasharn, Implacable Earth',
    'Rose, Cutthroat Raider',
    'Horn of Valhalla // Ysgard\'s Call',
    'Gimli\'s Reckless Might',
    'Growing Ranks',
    'Kefka, Court Mage // Kefka, Ruler of Ruin',
    'Grim Reaper\'s Sprint',
    'Teferi, Mage of Zhalfir',
    'Oblivion Ring',
    'Shay Cormac',
    'Terisian Mindbreaker',
    'Stolen Identity',
    'Faerie Conclave',
    'Saheeli, the Sun\'s Brilliance',
    'Viridian Longbow',
    'Unstable Amulet',
    'Fade from History',
    'Assemble the Players',
    'Mass Calcify',
    'Leyline of Transformation',
    'March of Progress',
    'Xyris, the Writhing Storm',
    'Barrowgoyf',
    'Samwise the Stouthearted',
    'Martial Impetus',
    'Ral, Monsoon Mage // Ral, Leyline Prodigy',
    'Sword of Hours',
    'Haunted One',
    'Silverwing Squadron',
    'Roaring Earth',
    'Apprentice Necromancer',
    'Spell Stutter',
    'Oviya, Automech Artisan',
    'Bant Panorama',
    'Ring of Valkas',
    'Path of Annihilation',
    'Into the North',
    'Indulging Patrician',
    'Goblin Chainwhirler',
    'Archmage of Echoes',
    'Firemind Vessel',
    'Pyre of Heroes',
    'Restless Vinestalk',
    'Restart Sequence',
    'Lux Artillery',
    'Hedron Detonator',
    'Infantry Shield',
    'Ob Nixilis, Captive Kingpin',
    'Jund Panorama',
    'Metalworker',
    'Titan\'s Strength',
    'Phyrexian Swarmlord',
    'Soaring Lightbringer',
    'Containment Priest',
    'Rith, Liberated Primeval',
    'The Deck of Many Things',
    'Izoni, Thousand-Eyed',
    'Fire Nation Palace',
    'Fblthp, Lost on the Range',
    'God-Eternal Rhonas',
    'Spear Spewer',
    'Zephyr Boots',
    'Maelstrom Nexus',
    'Submerge',
    'Hunted Horror',
    'Bant Charm',
    'Throat Slitter',
    'Tale\'s End',
    'Angel of Suffering',
    'Banquet Guests',
    'Thornglint Bridge',
    'Sarinth Steelseeker',
    'Olivia, Opulent Outlaw',
    'Nils, Discipline Enforcer',
    'Jori En, Ruin Diver',
    'Xolatoyac, the Smiling Flood',
    'Seasoned Dungeoneer',
    'Leyline of Hope',
    'Plague Stinger',
    'Liliana Vess',
    'Watcher of the Spheres',
    'The Thirteenth Doctor',
    'Gogo, Mysterious Mime',
    'World Breaker',
    'Sejiri Refuge',
    'Timberwatch Elf',
    'Zimone, Paradox Sculptor',
    'Hidden Courtyard',
    'Luck Bobblehead',
    'Angel of Invention',
    'Cid, Freeflier Pilot',
    'Of Herbs and Stewed Rabbit',
    'Aether Tunnel',
    'Khârn the Betrayer',
    'PuPu UFO',
    'Super State',
    'Thoughtseize',
    'Fortune Teller\'s Talent',
    'Collective Voyage',
    'Audacity',
    'Phylath, World Sculptor',
    'Remand',
    'Ichorclaw Myr',
    'Éomer, King of Rohan',
    'Rolling Hamsphere',
    'Drifting Meadow',
    'Season of the Burrow',
    'The Bath Song',
    'Bilious Skulldweller',
    'Mulch',
    'Sweet-Gum Recluse',
    'Coiling Rebirth',
    'Lush Oasis',
    'Crested Sunmare',
    'Angelic Skirmisher',
    'Unable to Scream',
    'Glass-Cast Heart',
    'The Raven Man',
    'Ruinous Intrusion',
    'Impassioned Orator',
    'Jaheira\'s Respite',
    'Nissa, Voice of Zendikar',
    'Ruric Thar, the Unbowed',
    'Brightcap Badger // Fungus Frolic',
    'Condemn',
    'Serpent of Yawning Depths',
    'Marchesa, the Black Rose',
    'Danitha, New Benalia\'s Light',
    'Knight of the Ebon Legion',
    'Kuja, Genome Sorcerer // Trance Kuja, Fate Defied',
    'Inquisitor\'s Flail',
    'Queza, Augur of Agonies',
    'Nullpriest of Oblivion',
    'Furnace of Rath',
    'Herald of Hoofbeats',
    'Metropolis Reformer',
    'Deranged Assistant',
    'Spiteful Sliver',
    'Kelpie Guide',
    'Badgermole Cub',
    'Malleable Impostor',
    'Urza\'s Factory',
    'Brute Force',
    'Grim Servant',
    'Gifted Aetherborn',
    'Black Waltz No. 3',
    'Glimmervoid',
    'Vat Emergence',
    'Dig Up',
    'Crossroads Village',
    'Treasure Chest',
    'Sporocyst',
    'Bugenhagen, Wise Elder',
    'Highway Robbery',
    'Oriq Loremage',
    'Thaumatic Compass // Spires of Orazca',
    'Entrapment Maneuver',
    'Cartographer\'s Hawk',
    'Triskelion',
    'Expand the Sphere',
    'Seafloor Oracle',
    'The Balrog of Moria',
    'Wan Shi Tong, Librarian',
    'Goblin Ringleader',
    'Distinguished Conjurer',
    'The Wanderer',
    'Redemption Arc',
    'Qasali Pridemage',
    'Trail of Crumbs',
    'Sylvan Awakening',
    'Undying Evil',
    'Satsuki, the Living Lore',
    'Skittering Invasion',
    'Plundering Barbarian',
    'Veinwitch Coven',
    'Bramble Sovereign',
    'Toralf, God of Fury // Toralf\'s Hammer',
    'Necrotic Ooze',
    'Lost Jitte',
    'Vexing Radgull',
    'Ba Sing Se',
    'Fractured Identity',
    'Earthcraft',
    'Tymna the Weaver',
    'Filigree Vector',
    'Kaya, Geist Hunter',
    'Mistcutter Hydra',
    'Cryptolith Fragment // Aurora of Emrakul',
    'Reverse the Polarity',
    'Contraband Livestock',
    'Ruthless Lawbringer',
    'Loyal Subordinate',
    'Cayth, Famed Mechanist',
    'Wondrous Crucible',
    'Tower Winder',
    'Quick Sliver',
    'Outrageous Robbery',
    'Elderfang Disciple',
    'Selvala\'s Stampede',
    'Aerial Surveyor',
    'Ramirez DePietro, Pillager',
    'The Magic Mirror',
    'Shoot the Sheriff',
    'Traveler\'s Amulet',
    'Duty Beyond Death',
    'Prophetic Prism',
    'Murderous Redcap',
    'Camaraderie',
    'Engulf the Shore',
    'Ancient Animus',
    'Essence Channeler',
    'Sorin, Lord of Innistrad',
    'Rabbit Battery',
    'Akroan Horse',
    'Secret Arcade // Dusty Parlor',
    'Putrid Goblin',
    'Squee, Goblin Nabob',
    'Restless Spire',
    'Wolfwillow Haven',
    'Tender Wildguide',
    'Scampering Surveyor',
    'Disorder in the Court',
    'Wizard\'s Retort',
    'Enter the Infinite',
    'Gilraen, Dúnedain Protector',
    'The Underworld Cookbook',
    'Stonehoof Chieftain',
    'Spiked Corridor // Torture Pit',
    'Citadel Siege',
    'Cadric, Soul Kindler',
    'Kroxa, Titan of Death\'s Hunger',
    'Legion Loyalist',
    'Deliberate',
    'Helix Pinnacle',
    'Chocobo Racetrack',
    'Trinisphere',
    'Act of Treason',
    'Song of Freyalise',
    'Profane Command',
    'Dazzling Denial',
    'Baneslayer Angel',
    'Maelstrom Colossus',
    'The Everflowing Well // The Myriad Pools',
    'Might of the Meek',
    'Ghost Vacuum',
    'Hidden Necropolis',
    'Quandrix Command',
    'Arvad the Cursed',
    'Shared Roots',
    'Splinterfright',
    'Rakdos, the Muscle',
    'Batterskull',
    'Far Traveler',
    'Sliver Legion',
    'Spit Flame',
    'Corsair Captain',
    'Thraben Watcher',
    'Faramir, Prince of Ithilien',
    'Elvish Rejuvenator',
    'Bloomvine Regent // Claim Territory',
    'Master of the Feast',
    'Eriette of the Charmed Apple',
    'Frenzied Baloth',
    'Bonehoard',
    'Steady Progress',
    'Arvinox, the Mind Flail',
    'Haze of Rage',
    'Aphetto Alchemist',
    'Flaming Fist',
    'Goldberry, River-Daughter',
    'Tunneling Geopede',
    'Stifle',
    'Phyrexian Revoker',
    'Saruman\'s Trickery',
    'Short Bow',
    'Iymrith, Desert Doom',
    'Tromokratis',
    'Curse of the Restless Dead',
    'Cloudsteel Kirin',
    'Beastcaller Savant',
    'Sunken Palace',
    'Chainsaw',
    'Nissa of Shadowed Boughs',
    'Minthara, Merciless Soul',
    'Season of Loss',
    'Deeproot Pilgrimage',
    'Olivia, Crimson Bride',
    'Insight Engine',
    'Felix Five-Boots',
    'Hero\'s Heirloom',
    'Squee, Dubious Monarch',
    'Song of Creation',
    'Riveteers Ascendancy',
    'Grist, Voracious Larva // Grist, the Plague Swarm',
    'Restless Prairie',
    'Suspicious Bookcase',
    'Shrieking Drake',
    'Dream Devourer',
    'Dimir Infiltrator',
    'Grand Warlord Radha',
    'Darksteel Reactor',
    'Green Sun\'s Twilight',
    'The Kami War // O-Kagachi Made Manifest',
    'Inkwell Leviathan',
    'Pain Distributor',
    'Goblin War Strike',
    'Erdwal Illuminator',
    'Haystack',
    'Lightning Runner',
    'Mishra\'s Workshop',
    'Vastwood Surge',
    'Sauron\'s Ransom',
    'Phenax, God of Deception',
    'Imotekh the Stormlord',
    'Psychotic Fury',
    'Brass Knuckles',
    'Cornered by Black Mages',
    'Magmakin Artillerist',
    'Response // Resurgence',
    'Dalkovan Encampment',
    'Woodland Stream',
    'Gollum, Obsessed Stalker',
    'Cliffhaven Vampire',
    'Anikthea, Hand of Erebos',
    'Anowon, the Ruin Sage',
    'Boon Reflection',
    'Dismantling Wave',
    'Capsize',
    'Venat, Heart of Hydaelyn // Hydaelyn, the Mothercrystal',
    'World Map',
    'Surge Conductor',
    'Deadly Recluse',
    'Attrition',
    'Silumgar, the Drifting Death',
    'Nerd Rage',
    'Pugnacious Hammerskull',
    'Back to Basics',
    'Orcish Siegemaster',
    'Final Act',
    'Ruin Grinder',
    'Alpha Deathclaw',
    'Rush of Dread',
    'Tomb Tyrant',
    'Shefet Dunes',
    'Bigger on the Inside',
    'Izzet Generatorium',
    'The Mycotyrant',
    'Leyline Prowler',
    'Ajani, Caller of the Pride',
    'Kumena, Tyrant of Orazca',
    'Sulfurous Mire',
    'Far Wanderings',
    'Relic of Progenitus',
    'Battlemage\'s Bracers',
    'Cast Out',
    'Haunting Voyage',
    'Nest of Scarabs',
    'Reflector Mage',
    'Apex of Power',
    'Gift of Estates',
    'Thieving Varmint',
    'On Wings of Gold',
    'Brallin, Skyshark Rider',
    'Knight of the Reliquary',
    'Foul Orchard',
    'Timestream Navigator',
    'Slimefoot, the Stowaway',
    'Flood Plain',
    'Terminus',
    'Unwanted Remake',
    'Last Chance',
    'Three Tree Mascot',
    'Fleet Swallower',
    'Cast into the Fire',
    'Reclaim',
    'Sorin, Vengeful Bloodlord',
    'Raffine, Scheming Seer',
    'Marang River Regent // Coil and Catch',
    'Great Unclean One',
    'Contest of Claws',
    'Geralf, Visionary Stitcher',
    'All-Out Assault',
    'Riptide Gearhulk',
    'Unsubstantiate',
    'Murmuration',
    'Necrotic Sliver',
    'Rogue Class',
    'Frodo, Adventurous Hobbit',
    'Fecundity',
    'Narset, Enlightened Exile',
    'Emet-Selch of the Third Seat',
    'Séance Board',
    'Gale, Waterdeep Prodigy',
    'HELIOS One',
    'Nylea\'s Intervention',
    'Cosima, God of the Voyage // The Omenkeel',
    'Felisa, Fang of Silverquill',
    'Betor, Kin to All',
    'Robe of the Archmagi',
    'Mardu Siegebreaker',
    'Drag to the Roots',
    'Nexos',
    'Smoke Bomb',
    'Rhonas the Indomitable',
    'Firespitter Whelp',
    'Empowered Autogenerator',
    'Clackbridge Troll',
    'Spear of Heliod',
    'Ishai, Ojutai Dragonspeaker',
    'Gossip\'s Talent',
    'Hare Apparent',
    'Elementalist\'s Palette',
    'Nightshade Harvester',
    'Klothys, God of Destiny',
    'Zurzoth, Chaos Rider',
    'Oblation',
    'Ornery Tumblewagg',
    'Overlord of the Mistmoors',
    'Barbarian Ring',
    'Stalking Vengeance',
    'Alela, Artful Provocateur',
    'Thieving Amalgam',
    'Life of the Party',
    'Angelfire Ignition',
    'Mindslaver',
    'Jegantha, the Wellspring',
    'The Master, Transcendent',
    'Avishkar Raceway',
    'Smash to Dust',
    'Loading Zone',
    'Possibility Storm',
    'Progenitor Mimic',
    'Zegana, Utopian Speaker',
    'Canopy Gargantuan',
    'Tangletrove Kelp',
    'Striking Sliver',
    'Winota, Joiner of Forces',
    'Multiversal Passage',
    'Thopter Assembly',
    'Storm of Souls',
    'Nahiri, Forged in Fury',
    'Hoard Hauler',
    'Ravenloft Adventurer',
    'Doomed Traveler',
    'Submerged Boneyard',
    'Nahiri\'s Resolve',
    'Filth',
    'Angelic Arbiter',
    'Glimmer Lens',
    'Redoubled Stormsinger',
    'Sea Gate Wreckage',
    'Retraction Helix',
    'Singularity Rupture',
    'Giant Ankheg',
    'Palace Siege',
    'Scroll of Isildur',
    'Entreat the Angels',
    'Alania, Divergent Storm',
    'Mercurial Spelldancer',
    'Bilbo\'s Ring',
    'Tuskguard Captain',
    'Ugin\'s Binding',
    'Aurora Phoenix',
    'Elspeth Resplendent',
    'Voyage Home',
    'Deep-Sea Kraken',
    'Mobilizer Mech',
    'The Pride of Hull Clade',
    'Repurposing Bay',
    'Magmaquake',
    'Mind Spring',
    'Loyal Drake',
    'Fevered Suspicion',
    'Blatant Thievery',
    'Dunes of the Dead',
    'Feather of Flight',
    'Kefnet\'s Monument',
    'Enterprising Scallywag',
    'Wrecking Ball Arm',
    'Captain Sisay',
    'Warren Warleader',
    'Glen Elendra Liege',
    'Raise the Alarm',
    'Fell Specter',
    'Ravenous Tyrannosaurus',
    'Lord Skitter\'s Butcher',
    'Akroma, Vision of Ixidor',
    'Screaming Nemesis',
    'Michiko\'s Reign of Truth // Portrait of Michiko',
    'Irregular Cohort',
    'Infesting Radroach',
    'Sarkhan the Masterless',
    'Mist-Syndicate Naga',
    'Slippery Karst',
    'Dimir House Guard',
    'Spinner of Souls',
    'Generous Ent',
    'Anafenza, Kin-Tree Spirit',
    'Salvation Engine',
    'Baldin, Century Herdmaster',
    'Rise of the Dread Marn',
    'Explore the Underdark',
    'Squirrel Sovereign',
    'Chameleon, Master of Disguise',
    'Roar of Resistance',
    'Offer Immortality',
    'Hellrider',
    'Thundermane Dragon',
    'The Lost and the Damned',
    'Galvanic Blast',
    'Sapphire Dragon // Psionic Pulse',
    'Senu, Keen-Eyed Protector',
    'Darksteel Juggernaut',
    'Nicanzil, Current Conductor',
    'Chainer, Dementia Master',
    'Nihil Spellbomb',
    'Teyo, Geometric Tactician',
    'Hanna, Ship\'s Navigator',
    'Breaker of Armies',
    'Quandrix Campus',
    'Gigantosaurus',
    'Necrogen Communion',
    'Loyal Inventor',
    'Needle Spires',
    'Sword of the Squeak',
    'Migratory Greathorn',
    'Archangel Elspeth',
    'Hollowmurk Siege',
    'Replication Technique',
    'The Seriema',
    'Obeka, Splitter of Seconds',
    'Wrexial, the Risen Deep',
    'Relentless Dead',
    'Gyome, Master Chef',
    'Syncopate',
    'Grimoire of the Dead',
    'Thunderherd Migration',
    'Nicol Bolas, the Ravager // Nicol Bolas, the Arisen',
    'Green Slime',
    'Sazacap\'s Brew',
    'Greta, Sweettooth Scourge',
    'Strength-Testing Hammer',
    'Ajani, Nacatl Pariah // Ajani, Nacatl Avenger',
    'Raphael, Fiendish Savior',
    'Dinosaurs on a Spaceship',
    'O\'aka, Traveling Merchant',
    'Karn, Living Legacy',
    'Defiler of Flesh',
    'Ancestors\' Aid',
    'Faerie Artisans',
    'Tanglespan Lookout',
    'Vodalian Hexcatcher',
    'Children of Korlis',
    'Beregond of the Guard',
    'Zoyowa\'s Justice',
    'Verdant Force',
    'Griffin Aerie',
    'Slip On the Ring',
    'Brought Back',
    'Terror Tide',
    'Finale of Promise',
    'Vanishing Verse',
    'Cataclysmic Gearhulk',
    'Aettir and Priwen',
    'Lock and Load',
    'The Ancient One',
    'Capture of Jingzhou',
    'Rampant Frogantua',
    'Pack Leader',
    'Ghostfire Slice',
    'Snarling Gorehound',
    'Angel of Jubilation',
    'Omnath, Locus of All',
    'Rile',
    'Roil Cartographer',
    'Titan of Littjara',
    'Goblin War Drums',
    'Goldhound',
    'Arbor Adherent',
    'Cosmic Hunger',
    'Nelly Borca, Impulsive Accuser',
    'Braids, Conjurer Adept',
    'RMS Titanic',
    'Display of Power',
    'Avenger of the Fallen',
    'Mirror Shield',
    'Perplexing Chimera',
    'Brotherhood Vertibird',
    'Tlincalli Hunter // Retrieve Prey',
    'Clive, Ifrit\'s Dominant // Ifrit, Warden of Inferno',
    'Vengeful Dead',
    'Finneas, Ace Archer',
    'Welcome to . . . // Jurassic Park',
    'Walking Bulwark',
    'Vastwood Hydra',
    'Hylda\'s Crown of Winter',
    'Beza, the Bounding Spring',
    'Krark\'s Thumb',
    'Champion of the Parish',
    'Kilo, Apogee Mind',
    'Angel of Despair',
    'Rundvelt Hordemaster',
    'Hidden Strings',
    'The Odd Acorn Gang',
    'Reef Worm',
    'Fiendlash',
    'Gaze of Granite',
    'Plumecreed Escort',
    'Instill Energy',
    'Fervent Charge',
    'Reverent Hoplite',
    'Djeru and Hazoret',
    'Tenza, Godo\'s Maul',
    'Arcane Heist',
    'Jackdaw Savior',
    'Vashta Nerada',
    'Omo, Queen of Vesuva',
    'Dawnsire, Sunstar Dreadnought',
    'Jumbo Cactuar',
    'Cathedral of War',
    'Infestation Sage',
    'Forlorn Flats',
    'Ajani Steadfast',
    'Risky Shortcut',
    'Stalwart Shield-Bearers',
    'Marneus Calgar',
    'Helga, Skittish Seer',
    'Invoke Calamity',
    'Bandit\'s Talent',
    'Ikra Shidiqi, the Usurper',
    'Oboro, Palace in the Clouds',
    'Witherbloom Apprentice',
    'Kari Zev, Skyship Raider',
    'Deathgreeter',
    'Desmond Miles',
    'Esix, Fractal Bloom',
    'Utopia Mycon',
    'Octomancer',
    'Dreadhound',
    'Stormchaser\'s Talent',
    'Trespasser\'s Curse',
    'Toothy, Imaginary Friend',
    'Mortivore',
    'Brood Sliver',
    'Skemfar Shadowsage',
    'Pontiff of Blight',
    'Lux Cannon',
    'Knight of Autumn',
    'Blasted Landscape',
    'Ambush Viper',
    'Karn, Scion of Urza',
    'Master Warcraft',
    'Mystic Retrieval',
    'Grixis Panorama',
    'Necrodominance',
    'Ryusei, the Falling Star',
    'Kastral, the Windcrested',
    'Chishiro, the Shattered Blade',
    'Vincent Valentine // Galian Beast',
    'Find // Finality',
    'Idol of False Gods',
    'Savage Order',
    'Platinum Emperion',
    'Primeval Herald',
    'Armadillo Cloak',
    'Ranger\'s Path',
    'Pir, Imaginative Rascal',
    'Tishana, Voice of Thunder',
    'Starwinder',
    'Narci, Fable Singer',
    'Cori Mountain Monastery',
    'Vampire Socialite',
    'Invasion of Segovia // Caetus, Sea Tyrant of Segovia',
    'Long-Term Plans',
    'Benevolent Blessing',
    'Agility Bobblehead',
    'Into the Roil',
    'Thada Adel, Acquisitor',
    'Battle Cry Goblin',
    'Counterflux',
    'Firkraag, Cunning Instigator',
    'Slaughter Pact',
    'Ramses, Assassin Lord',
    'Illuminor Szeras',
    'Pawpatch Formation',
    'Cemetery Prowler',
    'Teferi\'s Tutelage',
    'Go-Shintai of Life\'s Origin',
    'Elemental Eruption',
    'Ellivere of the Wild Court',
    'Hugs, Grisly Guardian',
    'Hall of Storm Giants',
    'Barkform Harvester',
    'Rat Colony',
    'Pariah\'s Shield',
    'Gravelighter',
    'Fandaniel, Telophoroi Ascian',
    'Voja, Jaws of the Conclave',
    'Orcish Medicine',
    'Delete',
    'Mauhúr, Uruk-hai Captain',
    'Merry, Warden of Isengard',
    'Raul, Trouble Shooter',
    'Lupinflower Village',
    'Electrosiphon',
    'Brainstone',
    'Lilysplash Mentor',
    'Parapet Thrasher',
    'Life Insurance',
    'Amoeboid Changeling',
    'The Last Agni Kai',
    'Brinelin, the Moon Kraken',
    'Callidus Assassin',
    'Splinter Twin',
    'Howling Moon',
    'Elspeth Tirel',
    'Faramir, Steward of Gondor',
    'You Find the Villains\' Lair',
    'Crypt Sliver',
    'Hadana\'s Climb // Winged Temple of Orazca',
    'Éomer, Marshal of Rohan',
    'Prize Pig',
    'Sudden Breakthrough',
    'Damping Sphere',
    'Festering Gulch',
    'Ainok Bond-Kin',
    'Gatecreeper Vine',
    'Benthic Biomancer',
    'Champions of Minas Tirith',
    'Sokrates, Athenian Teacher',
    'Ensnaring Bridge',
    'Arwen, Mortal Queen',
    'Mindless Automaton',
    'Silverclad Ferocidons',
    'Ankh of Mishra',
    'Scaretiller',
    'Retrofitter Foundry',
    'Flamekin Village',
    'Honden of Infinite Rage',
    'Abuelo, Ancestral Echo',
    'Sliver Hive',
    'Meloku the Clouded Mirror',
    'War\'s Toll',
    'Voldaren Epicure',
    'Abstruse Archaic',
    'Altered Ego',
    'Conspiracy',
    'Itzquinth, Firstborn of Gishath',
    'Sinew Sliver',
    'Make an Example',
    'High-Society Hunter',
    'Staff of Nin',
    'Cycle of Renewal',
    'Ghoulish Procession',
    'Mocking Doppelganger',
    'Subtlety',
    'Gemcutter Buccaneer',
    'Oran-Rief Hydra',
    'Urza, Lord Protector',
    'Omen Hawker',
    'Dalek Squadron',
    'Mind Grind',
    'Wandertale Mentor',
    'Languish',
    'Fungal Fortitude',
    'Glorious Gale',
    'Conspiracy Theorist',
    'Fell Stinger',
    'Molten Primordial',
    'Primal Command',
    'Smile at Death',
    'Wayward Servant',
    'Radiant Destiny',
    'Jace, the Perfected Mind',
    'Stitch in Time',
    'Spider Umbra',
    'Bloatfly Swarm',
    'Looter il-Kor',
    'Klauth\'s Will',
    'Brotherhood Headquarters',
    'Dawnglade Regent',
    'Hibernation Sliver',
    'Oblivion Stone',
    'Ancient Craving',
    'Blossoming Bogbeast',
    'Return from the Wilds',
    'Reluctant Role Model',
    'Share the Spoils',
    'Rocco, Cabaretti Caterer',
    'Star Athlete',
    'Sand Scout',
    'Tamiyo, the Moon Sage',
    'Oona\'s Blackguard',
    'Blinkmoth Urn',
    'Gallifrey Council Chamber',
    'Viewpoint Synchronization',
]